// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ConvertendoFahrenheitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void convertendoFahrenheit() {
    driver.get("http://localhost:8080/TermometroConversor/");
    driver.manage().window().setSize(new Dimension(550, 693));
    driver.findElement(By.name("fahr")).click();
    driver.findElement(By.name("fahr")).sendKeys("212");
    driver.findElement(By.cssSelector("form:nth-child(4) > input:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("h1:nth-child(2)")).getText(), is("Fahrenheit: 212.0"));
    assertThat(driver.findElement(By.cssSelector("h1:nth-child(1)")).getText(), is("Celsius: 100.0"));
  }
}
